services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: medusa
    volumes:
      - medusa-postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - medusa-redis-data:/data
    ports:
      - 6379:6379

  medusa:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
      - redis
    env_file:
      - .env.production
    ports:
      - 9000:9000

volumes:
  medusa-postgres-data:
  medusa-redis-data:
